#!/usr/bin/env python3
"""
Deal memo generation. Produces structured investment memos from scorecards.
Pattern from: startup-ecosystem-intelligence-mcp generate_deal_memo, M&A Playbook

Usage:
    python3 deal_memo.py "Booking Experts"
    python3 deal_memo.py --all    # Generate for all scored companies
"""

import json, os, sys, re
from datetime import datetime

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

from scoring import DIMS, WEIGHTS, WEIGHT_MAP, scan_red_flags, check_kill_criteria
from scoring import composite_to_grade, composite_to_readiness_score

BASE = os.path.join(os.path.dirname(__file__), '..')
HORECA_DIR = os.path.join(BASE, 'output', 'HORECA')


def load_scorecard(company_name_or_folder):
    """Load deep-analysis.md and extract structured data."""
    da = os.path.join(HORECA_DIR, company_name_or_folder, 'deep-analysis.md')
    if not os.path.exists(da):
        # Try as a company name
        folder = company_name_or_folder.lower().replace(' ', '-').replace('/', '-').replace('(', '').replace(')', '')
        folder = folder.replace("'", '').replace('&', 'and').replace('--', '-').strip('-')
        da = os.path.join(HORECA_DIR, folder, 'deep-analysis.md')
    if not os.path.exists(da):
        return None
    with open(da) as f:
        content = f.read()

    comp_match = re.search(r'\*\*Composite\*\*:\s*([\d.]+)\s*/\s*5\.0', content)
    composite = float(comp_match.group(1)) if comp_match else None

    scores = {}
    for dim in DIMS:
        pattern = r'\|\s*\d+\s*\|\s*' + re.escape(dim) + r'\s*\|\s*\w+\s*\|\s*([\d.]+)'
        m = re.search(pattern, content)
        if m:
            scores[dim] = float(m.group(1))

    title_match = re.search(r'^# (.+?) — Deep', content)
    name = title_match.group(1).strip() if title_match else company_name

    return {
        'name': name,
        'composite': composite,
        'dimensions': scores,
        'raw': content,
    }


def generate_memo(company_name):
    """Generate a structured deal memo for a company."""
    sc = load_scorecard(company_name)
    if not sc:
        return None

    grade = composite_to_grade(sc['composite'])
    red_flags = scan_red_flags(sc['dimensions'])
    kills = check_kill_criteria(sc['dimensions'])

    memo = f"""# Deal Memorandum — {sc['name']}

**Generated**: {datetime.now().strftime('%Y-%m-%d')}
**Status**: {'🔴 NOT RECOMMENDED' if kills else '🟢 FOR FURTHER REVIEW'}

---

## Executive Summary

| Metric | Value |
|---|---|
| Composite Score | {sc['composite']}/5.0 |
| Acquisition Readiness | {grade['score_100']}/100 |
| Grade | {grade['grade']} — {grade['description']} |
| Target Status | {'KILL CRITERIA TRIGGERED' if kills else 'Proceed with caution'} |

## Dimension Breakdown

| Dimension | Score | Weight |
|---|---|---|
"""
    for dim in DIMS:
        s = sc['dimensions'].get(dim, '?')
        w = WEIGHT_MAP.get(dim, 2)
        memo += f"| {dim} | {s} | {w}x |\n"

    memo += f"""
## Red Flags ({len(red_flags)})

"""
    if red_flags:
        for f in red_flags:
            memo += f"- [{f['severity'].upper()}] {f['message']}\n"
    else:
        memo += "No red flags detected.\n"

    memo += f"""
## Kill Criteria ({len(kills)})

"""
    if kills:
        for k in kills:
            memo += f"- **{k['name']}**: {k['message']}\n"
    else:
        memo += "No kill criteria triggered.\n"

    memo += f"""
## Recommendation

{'**DO NOT ACQUIRE** — Kill criteria triggered.' if kills else 
 '**CONSIDER ACQUISITION** — Further due diligence required.'}

---

*Auto-generated by SolStein M&A Pipeline*
"""
    return memo


def save_memo(company_name):
    """Generate and save deal memo to file."""
    memo = generate_memo(company_name)
    if not memo:
        print(f"  No scorecard found for {company_name}")
        return

    folder = company_name.lower().replace(' ', '-')
    out_dir = os.path.join(HORECA_DIR, folder)
    os.makedirs(out_dir, exist_ok=True)
    path = os.path.join(out_dir, 'deal-memo.md')
    with open(path, 'w') as f:
        f.write(memo)
    print(f"  Deal memo saved: {path}")
    return memo


if __name__ == '__main__':
    import sys
    if len(sys.argv) > 1 and sys.argv[1] == '--all':
        count = 0
        for d in sorted(os.listdir(HORECA_DIR)):
            dp = os.path.join(HORECA_DIR, d)
            if os.path.isdir(dp) and os.path.exists(os.path.join(dp, 'deep-analysis.md')) and d != 'Data':
                save_memo(d)
                count += 1
        print(f"\nGenerated {count} deal memos")
    else:
        name = sys.argv[1] if len(sys.argv) > 1 else 'Booking Experts'
        print(generate_memo(name) or f"No scorecard for {name}")
